### ISSUE TITLE
support simple neighbors

### ISSUE THREAD

**Issue by kiedtl** [cylgom/argoat#1]
In the README, you state that you don't support simple neighbors. I'm curious to know why.

**Comment by nullgemm** [comment]
Because I think they are misleading :D

With `test -abc42 1337 23` what is assigned to `a`, `b` and `c`? I would say `c` gets `42`, `a` gets `1337` and `b` `23`, but that would mean the first number is assigned to the last option, and then everything is processed in the right order again, weird...
If it is not the case and `a` gets `42`, `b` `1337` and `c` `23`, then why removing a simple ` `? It makes it look like the value is connected to the `c` when in reality it is not the case.
We could also implement them on non-compound options only, but saving a ` ` or a `=` isn't really worth the extra code IMHO.
I also happen to not have a perfect vision at all, and separating the options and their values helps improving readability.

So for all these reasons I chose not to add simple neighbors.

**Comment by kiedtl** [comment]
Thanks.
